name: CI/CD to EC2

on:
  push:
    branches: [ main ]  # use 'master' if your branch is named that

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Copy Files to EC2 via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        source: "."
        target: "~/devops-webapp"

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd devops-webapp
          docker stop $(docker ps -q) || true
          docker rm $(docker ps -a -q) || true
          docker build -t devops-webapp .
          docker run -d -p 8080:80 devops-webapp

